services:
  app: 
    build: .
    container_name: inventaris-app
    ports: 
      - "8080:8080"
    env_file:
      - .env 
    volumes: 
      - ./uploads:/app/uploads
    depends_on:
      - db

  db: 
    image: mysql:8.0
    container_name: inventaris-db
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
    mysql_data: {}