// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: produk/produk_request.proto

package produkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProdukReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProdukReq) Reset() {
	*x = GetProdukReq{}
	mi := &file_produk_produk_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProdukReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProdukReq) ProtoMessage() {}

func (x *GetProdukReq) ProtoReflect() protoreflect.Message {
	mi := &file_produk_produk_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProdukReq.ProtoReflect.Descriptor instead.
func (*GetProdukReq) Descriptor() ([]byte, []int) {
	return file_produk_produk_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetProdukReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_produk_produk_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_produk_produk_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_produk_produk_request_proto_rawDescGZIP(), []int{1}
}

var File_produk_produk_request_proto protoreflect.FileDescriptor

const file_produk_produk_request_proto_rawDesc = "" +
	"\n" +
	"\x1bproduk/produk_request.proto\x12\x06produk\"\x1e\n" +
	"\fGetProdukReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\a\n" +
	"\x05EmptyB\x17Z\x15inventarispb/produkpbb\x06proto3"

var (
	file_produk_produk_request_proto_rawDescOnce sync.Once
	file_produk_produk_request_proto_rawDescData []byte
)

func file_produk_produk_request_proto_rawDescGZIP() []byte {
	file_produk_produk_request_proto_rawDescOnce.Do(func() {
		file_produk_produk_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_produk_produk_request_proto_rawDesc), len(file_produk_produk_request_proto_rawDesc)))
	})
	return file_produk_produk_request_proto_rawDescData
}

var file_produk_produk_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_produk_produk_request_proto_goTypes = []any{
	(*GetProdukReq)(nil), // 0: produk.GetProdukReq
	(*Empty)(nil),        // 1: produk.Empty
}
var file_produk_produk_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_produk_produk_request_proto_init() }
func file_produk_produk_request_proto_init() {
	if File_produk_produk_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_produk_produk_request_proto_rawDesc), len(file_produk_produk_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_produk_produk_request_proto_goTypes,
		DependencyIndexes: file_produk_produk_request_proto_depIdxs,
		MessageInfos:      file_produk_produk_request_proto_msgTypes,
	}.Build()
	File_produk_produk_request_proto = out.File
	file_produk_produk_request_proto_goTypes = nil
	file_produk_produk_request_proto_depIdxs = nil
}
