// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: produk/produk_service.proto

package produkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_produk_produk_service_proto protoreflect.FileDescriptor

const file_produk_produk_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproduk/produk_service.proto\x12\x06produk\x1a\x1bproduk/produk_request.proto\x1a\x1cproduk/produk_response.proto2y\n" +
	"\rProdukService\x125\n" +
	"\rGetProdukById\x12\x14.produk.GetProdukReq\x1a\x0e.produk.Produk\x121\n" +
	"\fGetAllProduk\x12\r.produk.Empty\x1a\x12.produk.ProdukListB\x17Z\x15inventarispb/produkpbb\x06proto3"

var file_produk_produk_service_proto_goTypes = []any{
	(*GetProdukReq)(nil), // 0: produk.GetProdukReq
	(*Empty)(nil),        // 1: produk.Empty
	(*Produk)(nil),       // 2: produk.Produk
	(*ProdukList)(nil),   // 3: produk.ProdukList
}
var file_produk_produk_service_proto_depIdxs = []int32{
	0, // 0: produk.ProdukService.GetProdukById:input_type -> produk.GetProdukReq
	1, // 1: produk.ProdukService.GetAllProduk:input_type -> produk.Empty
	2, // 2: produk.ProdukService.GetProdukById:output_type -> produk.Produk
	3, // 3: produk.ProdukService.GetAllProduk:output_type -> produk.ProdukList
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_produk_produk_service_proto_init() }
func file_produk_produk_service_proto_init() {
	if File_produk_produk_service_proto != nil {
		return
	}
	file_produk_produk_request_proto_init()
	file_produk_produk_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_produk_produk_service_proto_rawDesc), len(file_produk_produk_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_produk_produk_service_proto_goTypes,
		DependencyIndexes: file_produk_produk_service_proto_depIdxs,
	}.Build()
	File_produk_produk_service_proto = out.File
	file_produk_produk_service_proto_goTypes = nil
	file_produk_produk_service_proto_depIdxs = nil
}
