// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: produk/produk_response.proto

package produkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Produk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nama          string                 `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	Deskripsi     string                 `protobuf:"bytes,3,opt,name=deskripsi,proto3" json:"deskripsi,omitempty"`
	Harga         float64                `protobuf:"fixed64,4,opt,name=harga,proto3" json:"harga,omitempty"`
	Kategori      string                 `protobuf:"bytes,5,opt,name=kategori,proto3" json:"kategori,omitempty"`
	Gambar        string                 `protobuf:"bytes,6,opt,name=gambar,proto3" json:"gambar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produk) Reset() {
	*x = Produk{}
	mi := &file_produk_produk_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produk) ProtoMessage() {}

func (x *Produk) ProtoReflect() protoreflect.Message {
	mi := &file_produk_produk_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produk.ProtoReflect.Descriptor instead.
func (*Produk) Descriptor() ([]byte, []int) {
	return file_produk_produk_response_proto_rawDescGZIP(), []int{0}
}

func (x *Produk) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Produk) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *Produk) GetDeskripsi() string {
	if x != nil {
		return x.Deskripsi
	}
	return ""
}

func (x *Produk) GetHarga() float64 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *Produk) GetKategori() string {
	if x != nil {
		return x.Kategori
	}
	return ""
}

func (x *Produk) GetGambar() string {
	if x != nil {
		return x.Gambar
	}
	return ""
}

type ProdukList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Produk              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProdukList) Reset() {
	*x = ProdukList{}
	mi := &file_produk_produk_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProdukList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdukList) ProtoMessage() {}

func (x *ProdukList) ProtoReflect() protoreflect.Message {
	mi := &file_produk_produk_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdukList.ProtoReflect.Descriptor instead.
func (*ProdukList) Descriptor() ([]byte, []int) {
	return file_produk_produk_response_proto_rawDescGZIP(), []int{1}
}

func (x *ProdukList) GetData() []*Produk {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_produk_produk_response_proto protoreflect.FileDescriptor

const file_produk_produk_response_proto_rawDesc = "" +
	"\n" +
	"\x1cproduk/produk_response.proto\x12\x06produk\"\x94\x01\n" +
	"\x06Produk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04nama\x18\x02 \x01(\tR\x04nama\x12\x1c\n" +
	"\tdeskripsi\x18\x03 \x01(\tR\tdeskripsi\x12\x14\n" +
	"\x05harga\x18\x04 \x01(\x01R\x05harga\x12\x1a\n" +
	"\bkategori\x18\x05 \x01(\tR\bkategori\x12\x16\n" +
	"\x06gambar\x18\x06 \x01(\tR\x06gambar\"0\n" +
	"\n" +
	"ProdukList\x12\"\n" +
	"\x04data\x18\x01 \x03(\v2\x0e.produk.ProdukR\x04dataB\x17Z\x15inventarispb/produkpbb\x06proto3"

var (
	file_produk_produk_response_proto_rawDescOnce sync.Once
	file_produk_produk_response_proto_rawDescData []byte
)

func file_produk_produk_response_proto_rawDescGZIP() []byte {
	file_produk_produk_response_proto_rawDescOnce.Do(func() {
		file_produk_produk_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_produk_produk_response_proto_rawDesc), len(file_produk_produk_response_proto_rawDesc)))
	})
	return file_produk_produk_response_proto_rawDescData
}

var file_produk_produk_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_produk_produk_response_proto_goTypes = []any{
	(*Produk)(nil),     // 0: produk.Produk
	(*ProdukList)(nil), // 1: produk.ProdukList
}
var file_produk_produk_response_proto_depIdxs = []int32{
	0, // 0: produk.ProdukList.data:type_name -> produk.Produk
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_produk_produk_response_proto_init() }
func file_produk_produk_response_proto_init() {
	if File_produk_produk_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_produk_produk_response_proto_rawDesc), len(file_produk_produk_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_produk_produk_response_proto_goTypes,
		DependencyIndexes: file_produk_produk_response_proto_depIdxs,
		MessageInfos:      file_produk_produk_response_proto_msgTypes,
	}.Build()
	File_produk_produk_response_proto = out.File
	file_produk_produk_response_proto_goTypes = nil
	file_produk_produk_response_proto_depIdxs = nil
}
